name: flutter_architecture
description: Flutter clean architecture app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  model_module:
    path: packages/model_module
  business_module:
    path: packages/business_module
  codegen_module:
    path:  packages/codegen_module

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
