name: business_module
description: Business module
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  injectable: ^1.5.3
  data_module:
    path: ../data_module
  model_module:
    path: ../model_module

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  injectable_generator: ^1.5.3
  build_runner: ^2.1.7
  dart_code_metrics: ^4.9.1
  analyzer_module:
    path: ../analyzer_module

flutter:
